# Generated by Django 2.0.4 on 2018-04-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teamdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(max_length=7)),
                ('teamname', models.CharField(max_length=80, unique=True)),
                ('itype', models.CharField(max_length=100)),
                ('iname', models.CharField(max_length=200)),
                ('irec', models.CharField(max_length=100)),
                ('tcap', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phn', models.CharField(max_length=10)),
                ('altphn', models.CharField(max_length=10)),
                ('coach', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('otp', models.IntegerField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('fblink', models.CharField(max_length=300)),
                ('fbactive', models.BooleanField()),
                ('payment1', models.BooleanField()),
                ('payment2', models.BooleanField()),
                ('payment1proof', models.CharField(max_length=500)),
                ('payment2proof', models.CharField(max_length=500)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.team')),
            ],
        ),
    ]
