# Generated by Django 2.0.4 on 2018-04-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='team',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
