# Generated by Django 2.0.4 on 2018-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180429_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='altphn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='coach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='fblink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='iname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='irec',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='itype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='otp',
            field=models.IntegerField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment1proof',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2proof',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='phn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='tcap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='teamid',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='teamname',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
