# Generated by Django 2.0.4 on 2018-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180429_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='otp',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
