# Generated by Django 2.0.4 on 2018-05-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180429_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='carnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='altphn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='coach',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='iname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='irec',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='itype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='phn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='tcap',
            field=models.CharField(max_length=100),
        ),
    ]
