# Generated by Django 2.0.4 on 2018-05-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180501_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
