# Generated by Django 2.0.4 on 2018-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180501_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
