# Generated by Django 2.0.4 on 2018-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_teamdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='email',
            field=models.CharField(default='ASD', max_length=100, unique=True),
        ),
    ]
