# Generated by Django 2.0.5 on 2018-05-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_teamdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phn', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bg', models.CharField(max_length=100)),
            ],
        ),
    ]
