# Generated by Django 2.0.5 on 2018-05-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_member_teamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default='NA', max_length=4),
        ),
    ]
