# Generated by Django 2.0.5 on 2018-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_member_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='payment1proof',
            field=models.FileField(upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2proof',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
