# Generated by Django 2.0.5 on 2018-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180521_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='payment1proof',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2proof',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
    ]
