# Generated by Django 2.0.5 on 2018-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180521_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='carnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment1proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
