# Generated by Django 2.0.5 on 2018-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180521_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='payment1proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
