# Generated by Django 2.0.5 on 2018-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180521_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(max_length=7)),
                ('phase', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
