# Generated by Django 2.0.5 on 2018-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
