# Generated by Django 2.0.5 on 2018-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_payments_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='gstindetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(default='NA', max_length=7)),
                ('lname', models.CharField(max_length=100)),
                ('addrs', models.CharField(default='NA', max_length=50)),
                ('gst', models.CharField(max_length=15)),
                ('sc', models.CharField(default='NA', max_length=2)),
            ],
        ),
    ]
