# Generated by Django 2.0.5 on 2018-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_gstindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstindetails',
            name='state',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
