# Generated by Django 2.0.5 on 2018-05-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_gstindetails_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenumber', models.CharField(max_length=20)),
                ('invoicedate', models.DateTimeField()),
                ('gstdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gstindetails')),
            ],
        ),
    ]
