# Generated by Django 2.0.5 on 2018-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='phase',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
