# Generated by Django 2.0.5 on 2018-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_invoice_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='teamlogo',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
