# Generated by Django 2.0.5 on 2018-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_teamdata_teamlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='size',
            field=models.IntegerField(blank=True),
        ),
    ]
