# Generated by Django 2.0.5 on 2018-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20180529_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='altphn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='otp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='phn',
            field=models.CharField(max_length=13),
        ),
    ]
