# Generated by Django 2.0.5 on 2018-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20180529_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(default='NA', max_length=7)),
                ('mname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phn', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('bg', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Unknown', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='Unknown', max_length=8),
        ),
    ]
