# Generated by Django 2.0.5 on 2018-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20180603_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(default='male.png', upload_to='profile/'),
        ),
    ]
