# Generated by Django 2.0.5 on 2018-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_member_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(default='members/male.png', upload_to='members/'),
        ),
    ]
