# Generated by Django 2.0.5 on 2018-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20180604_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='idproof',
            field=models.ImageField(default='/members/proof.png', upload_to=''),
        ),
    ]
