# Generated by Django 2.0.5 on 2018-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_member_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='idproof',
            field=models.ImageField(default='regatv..png', upload_to=''),
        ),
    ]
