# Generated by Django 2.0.5 on 2018-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20180604_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='idproof',
            field=models.ImageField(default='regback..png', upload_to=''),
        ),
    ]
