# Generated by Django 2.0.5 on 2018-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20180604_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(default='members/male.png', upload_to='members/'),
        ),
    ]
