# Generated by Django 2.0.5 on 2018-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20180604_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secret',
            field=models.CharField(default='', max_length=128),
        ),
    ]
