# Generated by Django 2.0.5 on 2018-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20180605_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='secret',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
