# Generated by Django 2.0.5 on 2018-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20180605_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberid',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]
