# Generated by Django 2.0.5 on 2018-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='entered',
            field=models.DateTimeField(default='2018-06-05 22:28:24'),
        ),
    ]
