# Generated by Django 2.0.5 on 2018-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_activitylog_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
