# Generated by Django 2.0.5 on 2018-07-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20180605_2247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gstindetails',
            unique_together={('teamid', 'gst')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('gstdet', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('teamid', 'phase')},
        ),
    ]
