# Generated by Django 2.1.5 on 2019-02-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20180729_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='carnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('booked', models.BooleanField()),
                ('teamid', models.CharField(default='NA', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='fbactive',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment1',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='payment2',
            field=models.BooleanField(blank=True),
        ),
    ]
