# Generated by Django 2.1.5 on 2019-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20190203_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnum',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
