# Generated by Django 2.1.5 on 2019-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20190203_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='memlimit',
            field=models.IntegerField(default=30),
        ),
    ]
