# Generated by Django 2.1.7 on 2019-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_teamdata_memlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifymobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
