# Generated by Django 2.1.7 on 2019-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_verifymobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='msglog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('phn', models.CharField(max_length=13)),
            ],
        ),
    ]
