# Generated by Django 2.1.7 on 2019-06-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_msglog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='msglog',
        ),
    ]
