# Generated by Django 2.1.7 on 2019-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_delete_msglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='state',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
