# Generated by Django 2.1.7 on 2020-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20190707_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='vtype',
            field=models.CharField(default='Combustion', max_length=20),
        ),
    ]
