# Generated by Django 2.1.11 on 2021-04-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_teamdata_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
