from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('teamreg/', views.teamreg, name='teamreg'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('addmember/', views.addteam, name='logout'),
    path('viewteam/', views.viewmember, name='viewteam'),
    path('editteam/', views.editteam, name='editteam'),
    path('editmem/', views.editmem, name='editmem'),
    path('deletemem/', views.deletemem, name='deletemem'),
    path('payment/', views.simple_upload, name='payment'),
    path('paymentinfo/', views.payinfo, name='payinfo'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('editp/', views.editp, name='editprofile'),
    path('invoices123456/', views.invoicer, name='geninvoice'),
    path('inv234566/', views.dwninvoice, name='dwninvoice'),
    path('base/', views.base, name='dwninvoice'),
    path('addfaculty/', views.addfac, name='dwninvoice'),
    path('viewfaculty/', views.viewfaculty, name='dwninvoice'),
    path('editfaculty/', views.editfaculty, name='dwninvoice'),
    path('editfac/', views.editfac, name='dwninvoice'),
    path('deletefac/', views.deletefac, name='dwninvoice'),
    path('verifymydetails/', views.comingsoon, name='dwninvoice'),
    path('lor/', views.viewlor),
    path('carnumber/', views.carnumber),
    path('booknumber/', views.confirmcarnum),
    path('bookingstatus/', views.bookingconf),
    path('registerteam/', views.newreg),
    path('verify-otp/', views.verifyotp),
    path('teamdetails/', views.teamdetails),
    # Additional URLs with views.portalclosed
    # path('addmember/', views.portalclosed, name='logout'),
    # path('viewteam/', views.viewmember, name='viewteam'),
    # path('editteam/', views.portalclosed, name='editteam'),
    # path('editmem/', views.portalclosed, name='editmem'),
    # path('deletemem/', views.portalclosed, name='deletemem'),
    # path('payment/', views.simple_upload, name='payment'),
    # path('paymentinfo/', views.payinfo, name='payinfo'),
    # path('editprofile/', views.portalclosed, name='editprofile'),
    # path('editp/', views.portalclosed, name='editprofile'),
    # path('invoices123456/', views.portalclosed, name='geninvoice'),
    # path('inv234566/', views.portalclosed, name='dwninvoice'),
    # path('base/', views.portalclosed, name='dwninvoice'),
    # path('addfaculty/', views.portalclosed, name='dwninvoice'),
    # path('viewfaculty/', views.portalclosed, name='dwninvoice'),
    # path('editfaculty/', views.portalclosed, name='dwninvoice'),
    # path('editfac/', views.portalclosed, name='dwninvoice'),
    # path('deletefac/', views.portalclosed, name='dwninvoice'),
    # path('verifymydetails/', views.portalclosed, name='dwninvoice'),
    path('lor/', views.viewlor),
    path('carnumber/', views.carnumber),
    path('booknumber/', views.confirmcarnum),
    path('bookingstatus/', views.bookingconf),
    path('registerteam/', views.teamdetails),
    path('verify-otp/', views.verifyotp),
    path('teamdetails/', views.teamdetails),
]
